[General]

background="#1D1D1D"
normalText="#ffffff"

rebootColor="#FF7800"
powerColor="#E01B24"

inputFields="#282828"
defaultbutton="#193D66"
hover="#1A5FB4"
topBar="#143152"
bottomBar""

successText="#2EC27E"
failureText="#ED333B"
warningText="#C64600"



primaryHue3="#282828"



primaryLight="#7986CB"
inputField="#303030"

primaryDark="#193D66"

accentShade="#143152"
accentFocus="#1A5FB4"
accentHover="#7986CB"

accentHue1="#FF669A" # Progress-bar
accentHue3="#E73677" # Progress-block



